;;; diredfd-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dired-fdclone.el

(define-obsolete-function-alias 'dired-fdclone #'diredfd-enable "2.0.0" "The package was renamed from `dired-fdclone' to `diredfd'; use `diredfd-enable' instead.")


;;; Generated autoloads from diredfd.el

(autoload 'diredfd-nav-mode "diredfd" "\
Toggle nav mode.

This is a minor mode.  If called interactively, toggle the `Diredfd-Nav
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `diredfd-nav-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'diredfd-find-file "diredfd" "\
Visit the current file or directory.")
(autoload 'diredfd-goto-top "diredfd" "\
Go to the top line of the current file list after `..'.
If the point is already at the top file, go to the beginning of the buffer." t)
(autoload 'diredfd-goto-bottom "diredfd" "\
Go to the bottom line of the current file list.
If the point is already at the bottom file, go to the end of the buffer." t)
(autoload 'diredfd-toggle-mark-here "diredfd" "\
Toggle the mark on the current line." t)
(autoload 'diredfd-toggle-mark "diredfd" "\
Toggle the mark on the current line and move to the next line.
Repeat ARG times if given.

If region is active, mark all the files in the region without moving the point.
If all files are already marked, unmark them instead.

(fn &optional ARG)" t)
(autoload 'diredfd-toggle-all-marks "diredfd" "\
Toggle all marks.

If region is active, toggle the marks in the region and keep the point." t)
(autoload 'diredfd-unmark-all-marks "diredfd" "\
Unmark all files in the Dired buffer.

If region is active, unmark all files in the region." t)
(autoload 'diredfd-mark-or-unmark-all "diredfd" "\
Mark or unmark all in the Dired buffer.

Unmark all files if there is any file marked, or mark all
non-directory files otherwise.

If ARG is given, mark all files including directories.

(fn &optional ARG)" t)
(autoload 'diredfd-narrow-to-marked-files "diredfd" "\
Kill all unmarked lines using `dired-kill-line'." t)
(autoload 'diredfd-narrow-to-files-regexp "diredfd" "\
Kill all lines except those matching REGEXP using `dired-kill-line'.

(fn REGEXP)" t)
(autoload 'diredfd-goto-filename "diredfd" "\
Jump to FILENAME.

(fn FILENAME)" t)
(autoload 'diredfd-do-shell-command "diredfd" "\
Open an ANSI terminal and run a COMMAND in it.

In COMMAND, the % sign is a meta-character and the following
macros are available.  All path names expanded will be escaped
with `shell-quote-argument'.

%P  -- Expands to the current directory name in full path.
%C  -- Expands to the name of the file at point.
%T  -- Expands to the names of the marked files, separated by
       spaces.
%M  -- Expands to the name of each marked file, repeating the
       command once for every marked file.
%X  -- Expands to the name of the file at point without the last
       suffix. (cf. `file-name-sans-extension')
%XM -- Expands to the name of each marked file without the last
       suffix, repeating the command once for every marked file.
%XT -- Expands to the names of the marked files without their
       last suffix, separated by spaces.
%%  -- Expands to a literal %.

(fn COMMAND)" t)
(autoload 'diredfd-do-flagged-delete-or-execute "diredfd" "\
Run `dired-do-flagged-delete' if any file is flagged for deletion.

If none is, run a shell command with all marked (or next ARG)
files or the current file.

For a list of macros usable in a shell command line, see
`diredfd-do-shell-command'.

(fn &optional ARG)" t)
(autoload 'diredfd-enter "diredfd" "\
Visit the current file, or enter if it is a directory." t)
(autoload 'diredfd-enter-directory "diredfd" "\
Enter DIRECTORY and jump to FILENAME.

(fn &optional DIRECTORY FILENAME)" t)
(autoload 'diredfd-enter-parent-directory "diredfd" "\
Enter the parent directory." t)
(autoload 'diredfd-enter-root-directory "diredfd" "\
Enter the root directory." t)
(autoload 'diredfd-history-backward "diredfd" "\
Go to the previous directory in history." t)
(autoload 'diredfd-history-forward "diredfd" "\
Go to the next directory in history." t)
(autoload 'diredfd-toggle-insert-subdir "diredfd" "\
Toggle the inserted subdirectory in the same buffer.

If the point is on a subdirectory, insert it below into the same
Dired buffer if not already present, and move the point to there.

Otherwise, remove the inserted subdirectory from the buffer and
go back to the parent in the same buffer." t)
(autoload 'diredfd-follow-symlink "diredfd" "\
Follow the symbolic link." t)
(autoload 'diredfd-view-file "diredfd" "\
Visit the current file in view mode." t)
(autoload 'diredfd-do-pack "diredfd" "\
Pack all marked (or next ARG) files, or the current file into an archive.

(fn &optional ARG)" t)
(autoload 'diredfd-pack "diredfd" "\
Pack FILES into ARCHIVE, asynchronously if ASYNC is non-nil.

(fn FILES ARCHIVE &optional ASYNC)")
(autoload 'diredfd-do-unpack "diredfd" "\
Unpack all marked (or next ARG) files or the current file.

(fn &optional ARG)" t)
(autoload 'diredfd-do-rename "diredfd" "\
Rename all marked (or next ARG) files, or invoke `wdired-mode'.

(fn &optional ARG)" t)
(autoload 'diredfd-help "diredfd" "\
Show the help window." t)
(autoload 'diredfd-mode "diredfd" "\
Toggle diredfd mode.

This is a minor mode.  If called interactively, toggle the `Diredfd
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `diredfd-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'diredfd-enable "diredfd" "\
Enable diredfd that makes `dired' look and feel like FD/FDclone.")
(autoload 'diredfd-disable "diredfd" "\
Disable diredfd that makes `dired' look and feel like FD/FDclone.")
(register-definition-prefixes "diredfd" '("diredfd-"))

;;; End of scraped data

(provide 'diredfd-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; diredfd-autoloads.el ends here
